config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions", :passwords => "passwords"}

  namespace :admin, as: :admin do
    resources :users, :only => [:index]
    resources :accounts, :only => [] do
      collection do
        get 'status'
      end
    end
    resources :transactions, :only => [:index] do
      collection do
        get 'csv'
      end
    end
  end

  scope module: :app do
    resources :banks, :only => [:index] do
      collection do
        get 'login_requirement'
        post  'login'
        post  'login_mfa'
        get 'popular'
      end
    end

    resources :accounts, :only => [:index, :create] do
      collection do
        post 'refresh'
        post 'refresh_all'
        post 'delete'
        post 'delete_all_unlinked'
      end
    end

    resources :transactions, :only => [:index] do
      collection do
        get 'dashboard'
        get 'balance'
        get 'query'
        get 'categories'
        post 'change_category'
      end
    end

  end

  scope module: :pages do
    get 'about'
    get 'services'
    get 'contact'
    post 'contact',                         action: :post_contact
    get 'faq'
    get 'terms-and-conditions',             action: :terms_and_conditions, as: :terms_and_conditions
    get 'privacy-policy',                   action: :privacy_policy, as: :privacy_policy
  end

  get 'users/me', to: 'users#me'

  get '*path', to: 'application#index'

  get '/', :controller=> 'application',:action=>'index'

  root :to => 'application#index'


end

app/views/layouts/_admin_header.html.slim
header.main-header
  a.logo href= "#"
    b SAVE
    | RD
  /! Header Navbar: style can be found in header.less
  nav.navbar.navbar-static-top role="navigation"
    /! Sidebar toggle button
    a.sidebar-toggle data-toggle="offcanvas" href="#" role="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    .navbar-custom-menu
      ul.nav.navbar-nav

app/views/layouts/_admin_sidebar.html.slim
.aside.main-sidebar
  /! sidebar: style can be found in sidebar.less
  section.sidebar
    /! Sidebar user panel
    .user-panel
      .pull-left.image
    ul.sidebar-menu
      li.header MAIN NAVIGATION

      li.treeview
        =link_to admin_users_path do
          i.fa.fa-dashboard
          span Users
          i.fa.fa-angle-left.pull-right
      li.treeview
        =link_to admin_transactions_path do
          i.fa.fa-dashboard
          span Transactions
          i.fa.fa-angle-left.pull-right
      li.treeview
        =link_to status_admin_accounts_path do
          i.fa.fa-dashboard
          span Yodlee Status
          i.fa.fa-angle-left.pull-right

app/views/layouts/admin_application_layout.html.slim
doctype html
html lang="en"
  - @page_attrs = @page_attrs || {}
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'
    title= content_for?(:title) ? yield(:title) : "SaveRD"
    = csrf_meta_tags

    link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css"
    link href='http://fonts.googleapis.com/css?family=Open+Sans:400,500,600,700,800,300,200,100' rel='stylesheet' type='text/css'
    link href='//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' rel='stylesheet' type='text/css'

    = stylesheet_link_tag "admin/admin", :media => "all"

    /![if lt IE 9]
      | <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script
      | <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script

    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"
    = javascript_include_tag "admin/admin"

  body.skin-blue
    == render 'layouts/admin_header'
    == render 'layouts/admin_sidebar'
    = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title Yodlee
    link href='https://fonts.googleapis.com/css?family=Quicksand:400,700,300' rel='stylesheet' type='text/css'
    meta name="viewport" content="width=device-width"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
    = javascript_include_tag 'application'
    = csrf_meta_tags
    base href="/"
  body ng-app="appModule"
    = yield